# Generated by Django 4.2.16 on 2024-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(unique=True, upload_to="reference_tracks/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Piano", "Piano"),
                            ("Guitar", "Guitar"),
                            ("Drum", "Drum"),
                            ("Vocals", "Vocals"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
