# Generated by Django 4.2.16 on 2024-11-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_management', '0002_referencetracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
