# Generated by Django 4.2.16 on 2024-11-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_management', '0003_alter_audiotrack_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenceTracks',
        ),
    ]
