steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Majefashek/repleet_backend.git']

  # Step 2: SSH into your VM and pull latest changes
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'compute', 'ssh', 'abdullahishuaibumaje@fixedreepeet@104.197.17.121',
      '--project', '$repeetbackendproject', '--zone', 'your-zone',
      '--command', '/home/abdullahishuaibumaje/repleet_backend && git pull && docker-compose down && docker-compose up -d'
    ]

# Adding the solution for logging (Option 1, 2, or 3 as discussed above)
options:
  logging: CLOUD_LOGGING_ONLY  # You can change this if you want a storage bucket
  # logsBucket: gs://your-logs-bucket  # Uncomment and set your bucket if you want a logs bucket
