version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:9000"
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - celery
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1

  celery:
    build: .
    command: celery -A repleet_backend worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
