# Generated by Django 5.1.3 on 2024-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.CharField(choices=[('Piano', 'Piano'), ('Guitar', 'Guitar'), ('Drum', 'Drum'), ('Vocals', 'Vocals')], default='Piano', max_length=20),
        ),
    ]
